pokerth_lib.pro: Add qttoolswrapper.cpp and qthelper.cpp to source
Introduced with c++20.

Don't remove 'core' from QT to fix QtCore inclusion.

/usr/bin/ld: lib/libpokerth_lib.a(configfile.o): in function `ConfigFile::ConfigFile(char*, bool)':
configfile.cpp:(.text+0x5e2a): undefined reference to `CreateQtToolsWrapper()'

/usr/bin/ld: lib/libpokerth_lib.a(qttoolswrapper.o): in function `QtToolsWrapper::~QtToolsWrapper()':
qttoolswrapper.cpp:(.text+0x28): undefined reference to `QtHelper::~QtHelper()'