chatcleaner.pro: Add libs to linker
Introduced with c++20

rypthelper.cpp:(.text+0x304): undefined reference to `gcry_md_open'
/usr/bin/ld: crypthelper.cpp:(.text+0x318): undefined reference to `gcry_md_write'
/usr/bin/ld: crypthelper.cpp:(.text+0x343): undefined reference to `gcry_md_read'
/usr/bin/ld: crypthelper.cpp:(.text+0x372): undefined reference to `gcry_md_close'

etc.