pokerth_lib.pro: Add loghelper_client.cpp to source
Introduced with c++20.

usr/bin/ld: lib/libpokerth_lib.a(configfile.o): in function `ConfigFile::fillBuffer()':
configfile.cpp:(.text+0x2e6b): undefined reference to `internal_log_err(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: lib/libpokerth_lib.a(configfile.o): in function `ConfigFile::updateConfig(ConfigState)':
configfile.cpp:(.text+0x4ce8): undefined reference to `internal_log_err(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: lib/libpokerth_lib.a(configfile.o): in function `ConfigFile::ConfigFile(char*, bool)':